apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-orders-mapping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-orders-mapping
  template:
    metadata:
      labels:
        app: customer-orders-mapping
    spec:
      containers:
      - name: customer-orders-mapping
        image: ernivasit/customer-orders-mapping:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80